config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :snippets do
    # resources :kinds, only: [:show]
  end
  resources :kinds

  root 'snippets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :snippets

  validates :name, { presence: true, uniqueness: true }
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :kind

  validates :kind, presence: true
  validates :title, presence: true, uniqueness: true
  validates :work, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  def show
    @snippets = Snippet.where(kind_id: params[:id])
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
   before_action :find_snippet, only: [:show, :edit, :update, :destroy]

   def index
     @snippets = Snippet.all
     @kinds = Kind.all
   end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new snippet_params
    if @snippet.save
      redirect_to snippet_path(@snippet), notice: 'Snippet Created'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @snippet.update snippet_params
      redirect_to @snippet
    else
      render :edit
    end
  end

  def destroy
    @snippet.destroy
    redirect_to root_path
  end



private

  def snippet_params
    params.require(:snippet).permit(:title, :work, :kind_id)
  end

  def find_snippet
    @snippet = Snippet.find params[:id]
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/kinds/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-lg-offset(-8)">
      <% @snippets.each do |snippet| %>
        <h1><%= snippet.title %></h1>
        <p><%= CodeRay.scan(snippet.work, snippet.kind.name).div(:line_numbers => :table).html_safe %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeSnippets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <%= link_to 'All Snippets', snippets_path %> |
    <%= link_to 'New Snippet', new_snippet_path %> |
  </div>
</nav>


    <%= yield %>
  </body>
</html>

app/views/snippets/_form.html.erb
  <div class="row">
    <div class="col-md-4 col-md-offset(-8)">
      <%= @snippet.errors.full_messages.join(', ') %>

      <%= form_for @snippet do |f| %>
      <div class="form-group">
        <%= f.label :kind %>
        <%= f.collection_select :kind_id, Kind.all, :id, :name,
        {},
        { class: 'chosen-select form-control' } %>
      </div>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :work %>
        <%= f.text_area :work, class: 'form-control', rows: 8 %>
      </div>
      <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>

app/views/snippets/edit.html.erb
<div class="container">
  <h1>Edit Snippet</h1>

  <%= render 'form' %>
</div>

app/views/snippets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset(8)">
      <h1>Code Snippets</h1>

      <% @kinds.each do |kind| %>
        <h3 class='well'><%= link_to "#{kind.name} (#{Snippet.where(kind_id: kind.id).count} snippets)", kind_path(kind.id) %></h3>
      <% end %>

    </div>
  </div>
</div>

app/views/snippets/new.html.erb
<div class="container">
  <h1>New Code Snippet</h1>

  <%= render 'form' %>

</div>

app/views/snippets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h1><%= @snippet.title %></h1>
      <%= CodeRay.scan(@snippet.work, :ruby).div(:line_numbers => :table).html_safe %>
      <%= link_to "Edit", edit_snippet_path(@snippet), class: "btn btn-default" %>
      <%= link_to "Delete", snippet_path(@snippet), method: :delete,
                                                   data: { confirm: "Are you sure?"}, class: "btn btn-default" %>
    </div>
  </div>
</div>